### PR TITLE
Add support for 'random' option in skin_tone

### PR DESCRIPTION
**Pull request by oscard0m**
Fix #46

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
This would need to be opt-in. How do you provide such functionality?

**Comment by dominguezcelada** [comment]
> This would need to be opt-in.

Thanks for the fast response. What do you mean by *this would need to be opt-in*? @jsumners 

Thanks

**Comment by jsumners** [comment]
Your change makes every invocation of the workflow return a random skin tone. The workflow prior to this change has an environment variable set that determines the skin tone that is returned on every invocation of the workflow. So this changes the default behavior for all users, whereas users that want the randomness should have to specify that they want it.

**Comment by dominguezcelada** [comment]
> Your change makes every invocation of the workflow return a random skin tone. The workflow prior to this change has an environment variable set that determines the skin tone that is returned on every invocation of the workflow. So this changes the default behavior for all users, whereas users that want the randomness should have to specify that they want it.

Only if the environment variable is set as `random` is my intention. Maybe I-m missing something else?

https://github.com/jsumners/alfred-emoji/pull/46/files#diff-78e2dfe66a33c5b8166c8790b4be6d497d5b32c985cce791b4fcc520247b614cR21-R23

```
function getSkinTone() {
  const skinTone = getEnv('skin_tone');
  if(skinTone === 'random') {
    return getRandomSkinTone()
  }

  return skinTone
}
```

**Comment by jsumners** [comment]
Sorry. I didn't read the minimal code carefully enough.

**Review by jsumners — APPROVED** [review]
LGTM

**Comment by dominguezcelada** [comment]
> Sorry. I didn't read the minimal code carefully enough.

no problem. I'll go for tests and README update later and open a final PR. 

Thanks for the quick answer

**Review by jsumners — APPROVED** [review]
LGTM

**Comment by dominguezcelada** [comment]
Is there something else I need to do from my end @jsumners ? 

Thankd :)

**Comment by jsumners** [comment]
No. I need to solve #47 before I'm ready to merge this. See the readme on my profile https://github.com/jsumners

**Review by jsumners — APPROVED** [review]

**Comment by jsumners** [comment]
https://github.com/jsumners/alfred-emoji/releases/tag/v1.10.0

**Pull request merged**
