### PR TITLE
Update to use emojilib v3

### PR DESCRIPTION
**Pull request by jsumners**

### CODE REVIEW

**Comment by devnoname120** [comment]
Emoji search is significantly slower since this PR was merged.

Hypothesized culprits:
- Iterating on the objects of `orderedEmoji` is slower than on the primitive type strings of `emojiNames`.
- The new lib has an order of magnitude more emojis. Search is `O(n)` where `n` is the number of emojis. It's possible that `n` got considerably bigger.

**Comment by devnoname120** [comment]
Here is a fork that uses v2 if anyone has the same issue in the future: https://github.com/devnoname120/alfred-emoji/releases/tag/v1.11.0

**Comment by jsumners** [comment]
Please work with us instead of immediately starting forks. There has not been a new version published that utilizes the code in this PR as yet. There is plenty of time to work out issues before such happens.

**Comment by devnoname120** [comment]
I don't plan to maintain the fork. It's just a quick and dirty solution (mostly for personal use) because I don't plan to invest time fixing the root issue in the short term.

**Comment by devnoname120** [comment]
@jsumners I can confirm that the performance issues I was experiencing are resolved now.

**Pull request merged**
